### ISSUE TITLE
Do you have the Astroprocessor source code that is not in Wordpress

### ISSUE THREAD

**Issue by mienv567** [lDeNl/astro#1]
Is there any conflict with https://karmision.ru/astroprocessor/ The same Astroprocessor source code, I saw the latest version on the website

**Comment by mienv567** [comment]
@lDeNl  在不

**Comment by mienv567** [comment]
@lDeNl

**Comment by lDeNl** [comment]
No, it's code for commercial project

**Comment by lDeNl** [comment]
.

**Comment by mienv567** [comment]
Okay, sorry, there is a slight bug in the code in Github right now, which is that some of the text in the image you placed is not displayed in the position of the star chart
